source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '7.0'
pod "AFNetworking", "~> 2.0"
pod 'libextobjc', '~> 0.4'
pod 'MBProgressHUD', '~> 0.8'
pod 'BlocksKit', '~> 2.2.3'
pod 'SDWebImage', '~> 3.7.1'
pod 'ReactiveCocoa', '~> 2.3.1'
pod 'StandardPaths', '~> 1.6.3'
pod 'KVOController'
